server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 7001
database:
  driverClass: org.postgresql.Driver
  user: nfw
  password: nfw
  url: jdbc:postgresql://localhost/nfw
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: validate
    hibernate.show_sql: true
    hibernate.format_sql: true
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  minSize: 8
  maxSize: 16
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute