server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 7001
database:
#  driverClass: org.postgresql.Driver
  driverClass: org.h2.Driver
#  user: nfw
#  password: nfw
#  url: jdbc:postgresql://localhost/nfw

  user: sa
  password: sa
  url: jdbc:h2:./target/nfw

  properties:
    charSet: UTF-8
#    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
    hibernate.show_sql: true
    hibernate.format_sql: true
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  minSize: 8
  maxSize: 16
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute